@startuml
'
' Resource:  SubmitProductOrder
' Source:    TMF622-ProductOrdering-v5.0.0.oas.yaml
'
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BorderColor<<Extension>> blue
   FontColor<<Extension>> blue
   backgroundColor<<Enumeration>> #E6F5F7
   backgroundColor<<Ref>> #FFFFE0
   backgroundColor<<Pivot>> #FFFFFFF
   backgroundColor<<Resource>> #FCF2E3
   backgroundColor<<SubResource>> #FFFFFFF
   backgroundColor<<SubResourceReference>> #FADADD
}

skinparam legend {
   borderRoundCorner 0
   borderColor red
   backgroundColor white
}

class SubmitProductOrder <extends  \nEntity>  <<Pivot>> <<Extension>> {
    {field}creationDate : DateTime (1)
    {field}effectiveSubmissionDate : DateTime (1)
    {field}href : String (1)
    {field}id : String (1)
    {field}state : TaskStateType (1)
    @baseType : String
    @schemaLocation : String
    {field}@type : String (1)
}

class TaskStateType <<Enumeration>> {
    acknowledged
    inProgress
    rejected
    terminatedWithError
    cancelled
    done
}

class ProductOrderRef <extends  \n<color:blue>Extensible\n<color:blue>Reference\n<color:blue>EntityRef>  <<Ref>> {
    href : String
    {field}id : String (1)
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : String
    <color:blue>{field}@type : String (1)
}

SubmitProductOrder -right[hidden]-> TaskStateType

SubmitProductOrder *-[#blue]->  "0..1" ProductOrderRef : <color:blue>productOrder




skinparam legendBackgroundColor #transparent
skinparam legendBorderColor #transparent

legend
   |= <size:10>Color |= <size:10>Description |
   | <#FFFFFFF> | <size:10>Resource (entry point) |
   | <#FFFFE0> | <size:10>Sub-resource (reference entity) |
   | <#E6F5F7> | <size:10>Enumeration |
   | <#blue> | <size:10>added |
 <size:10>(1) : Mandatory property
endlegend

@enduml