@startuml
'
' Resource:  ProductValue
' Source:    TMF622-ProductOrdering-v5.0.0.oas.yaml
'
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BorderColor<<Extension>> blue
   FontColor<<Extension>> blue
   backgroundColor<<Enumeration>> #E6F5F7
   backgroundColor<<Ref>> #FFFFE0
   backgroundColor<<Pivot>> #FFFFFFF
   backgroundColor<<Resource>> #FCF2E3
   backgroundColor<<SubResource>> #FFFFFFF
   backgroundColor<<SubResourceReference>> #FADADD
}

skinparam legend {
   borderRoundCorner 0
   borderColor red
   backgroundColor white
}

class ProductValue <extends  \nExtensible>  <<SubResource>> <<Extension>> {
    creationDate : DateTime
    description : String
    href : String
    id : String
    isBundle : Boolean
    isCustomerVisible : Boolean
    name : String
    orderDate : DateTime
    productSerialNumber : String
    startDate : DateTime
    status : ProductStatusType
    terminationDate : DateTime
    @baseType : String
    @schemaLocation : String
    {field}@type : String (1)
}

class ProductStatusType <<Enumeration>> {
    pendingTerminate
    created
    cancelled
    active
    pendingActive
    aborted 
    terminated
    suspended
}

class ProductOfferingRef <extends  \n<color:blue>Extensible\n<color:blue>Reference\n<color:blue>EntityRef>  <<Ref>> {
    href : String
    {field}id : String (1)
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : String
    <color:blue>{field}@type : String (1)
}

class ProductPrice <extends  \n<color:blue>Extensible> <<Resource>> {
    description : String
    name : String
    priceType : String
    recurringChargePeriod : String
    unitOfMeasure : String
    @baseType : String
    @schemaLocation : <color:blue>String
    <color:blue>{field}@type : String (1)
}

class ProductRef <extends  \n<color:blue>Extensible\n<color:blue>Reference\n<color:blue>EntityRef>  <<Ref>> {
    href : String
    {field}id : String (1)
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : String
    <color:blue>{field}@type : String (1)
}

class PlaceRef <extends  \n<color:blue>Extensible\n<color:blue>Reference\n<color:blue>EntityRef>  <<Ref>> {
    href : String
    {field}id : String (1)
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : String
    <color:blue>{field}@type : String (1)
}

class GeographicAddressValue <extends  \nExtensible> <<Resource>> <<Extension>> {
    city : String
    country : String
    locality : String
    postcode : String
    stateOrProvince : String
    streetName : String
    streetNr : String
    streetNrLast : String
    streetNrLastSuffix : String
    streetNrSuffix : String
    streetSuffix : String
    streetType : String
    @baseType : String
    @schemaLocation : String
    {field}@type : String (1)
}

class PriceAlteration <extends  \n<color:blue>Extensible> <<Resource>> {
    applicationDuration : Integer
    description : String
    name : String
    <color:blue>{field}priceType : String (1)
    priority : Integer
    recurringChargePeriod : String
    unitOfMeasure : String
    @baseType : String
    @schemaLocation : <color:blue>String
    <color:blue>{field}@type : String (1)
}

class ProductOfferingPriceRef <extends  \n<color:blue>Extensible\n<color:blue>Reference\n<color:blue>EntityRef>  <<Ref>> {
    href : String
    {field}id : String (1)
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : String
    <color:blue>{field}@type : String (1)
}

class ProductRelationship <extends  \n<color:blue>Extensible\n<color:blue>EntityRef>  <<Ref>> {
    <color:blue>href : String
    <color:blue>id : String
    relationshipType : String
    @baseType : String
    @schemaLocation : <color:blue>String
    <color:blue>{field}@type : String (1)
}

class GeographicLocationValue <extends  \nExtensible> <<Resource>> <<Extension>> {
    bbox : Number [0..*]
    @baseType : String
    @schemaLocation : String
    {field}@type : String (1)
}

class RelatedPlaceRefOrValue <<Resource>> {
    {field}//                                        //
    --
    discriminator:
    <color:blue>GeographicAddress
    <color:blue>GeographicLocation
    <color:blue>RelatedPlaceRefOrValue
    <color:blue>PlaceRef
}

class ProductTerm <extends  \n<color:blue>Extensible> <<Resource>> {
    description : String
    duration : <color:blue>Duration
    name : String
    validFor : TimePeriod
    @baseType : String
    @schemaLocation : <color:blue>String
    <color:blue>{field}@type : String (1)
}

class BillingAccountRef <extends  \n<color:blue>Extensible\n<color:blue>Reference\n<color:blue>EntityRef>  <<Ref>> {
    href : String
    {field}id : String (1)
    name : String
    ratingType : String
    @baseType : String
    @referredType : String
    @schemaLocation : <color:blue>String
    <color:blue>{field}@type : String (1)
}

class Characteristic <extends  \n<color:blue>Extensible>  <<SubResourceReference>> {
    characteristicRelationship : CharacteristicRelationship [0..*]
    id : String
    name : String
    valueType : String
    @baseType : String
    @schemaLocation : <color:blue>String
    <color:blue>{field}@type : String (1)
    --
    discriminator:
    <color:blue>ObjectCharacteristic
    <color:blue>NumberCharacteristic
    <color:blue>BooleanArrayCharacteristic
    <color:blue>Characteristic
    <color:blue>NumberArrayCharacteristic
    <color:blue>BooleanCharacteristic
    <color:blue>ObjectArrayCharacteristic
    <color:blue>IntegerCharacteristic
    <color:blue>StringArrayCharacteristic
    <color:blue>IntegerArrayCharacteristic
    <color:blue>StringCharacteristic
}

class GeographicSubAddressUnit <extends  \nExtensible> <<Resource>> <<Extension>> {
    subUnitNumber : String
    subUnitType : String
    @baseType : String
    @schemaLocation : String
    {field}@type : String (1)
}

class ProductRefOrValue <<Resource>> {
    {field}//                                        //
    --
    discriminator:
    <color:blue>Product
    <color:blue>ProductRef
}

class Price <extends  \n<color:blue>Extensible> <<Resource>> {
    dutyFreeAmount : Money
    percentage : Float
    taxIncludedAmount : Money
    taxRate : Float
    @baseType : String
    @schemaLocation : <color:blue>String
    <color:blue>{field}@type : String (1)
}

class GeographicSubAddressValue <extends  \nExtensible> <<Resource>> <<Extension>> {
    buildingName : String
    levelNumber : String
    levelType : String
    name : String
    privateStreetName : String
    privateStreetNumber : String
    subAddressType : String
    @baseType : String
    @schemaLocation : String
    {field}@type : String (1)
}

class RelatedOrderItem <extends  \nExtensible> <<Resource>> <<Extension>> {
    orderHref : String
    orderId : String
    orderItemAction : ItemActionType
    orderItemId : String
    role : String
    @baseType : String
    @referredType : String
    @schemaLocation : String
    {field}@type : String (1)
}

class ItemActionType <<Enumeration>> {
    add
    modify
    noChange
    delete
}

class AgreementItemRef <extends  \n<color:blue>Extensible> <<Resource>> {
    <color:blue>agreementHref : String
    <color:blue>agreementId : String
    agreementItemId : String
    <color:blue>agreementName : String
    @baseType : String
    @referredType : String
    @schemaLocation : String
    <color:blue>{field}@type : String (1)
}

class RelatedParty <extends  \n<color:blue>Extensible\n<color:blue>Reference\n<color:blue>EntityRef>  <<Ref>> {
    href : String
    {field}id : String (1)
    name : String
    role : String
    @baseType : String
    @referredType : String
    @schemaLocation : String
    <color:blue>{field}@type : String (1)
}

class ResourceRef <extends  \n<color:blue>Extensible\n<color:blue>Reference\n<color:blue>EntityRef>  <<Ref>> {
    href : String
    {field}id : String (1)
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : String
    <color:blue>{field}@type : String (1)
}

class ServiceRef <extends  \n<color:blue>Extensible\n<color:blue>Reference\n<color:blue>EntityRef>  <<Ref>> {
    href : String
    {field}id : String (1)
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : String
    <color:blue>{field}@type : String (1)
}

class ProductSpecificationRef <extends  \n<color:blue>Extensible\n<color:blue>Reference\n<color:blue>EntityRef>  <<Ref>> {
    href : String
    {field}id : String (1)
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : String
    <color:blue>{field}@type : String (1)
}

ProductValue -right[hidden]-> ProductStatusType

ProductValue *-[#blue]->  "0..*" RelatedOrderItem : <color:blue>productOrderItem

ProductValue *-[#blue]->  "0..*" ProductRefOrValue : <color:blue>product

ProductValue *-[#blue]->  "0..*" RelatedPlaceRefOrValue : <color:blue>place

ProductValue *-[#blue]->  "0..*" ProductPrice : <color:blue>productPrice

RelatedOrderItem -right[hidden]-> ItemActionType

RelatedPlaceRefOrValue ..> GeographicAddressValue

ProductRefOrValue .left.> ProductValue

ProductPrice *-left-> "0..1" ProductOfferingPriceRef : productOfferingPrice

RelatedPlaceRefOrValue -left[hidden]- ProductPrice

ProductOfferingPriceRef "0..1" <--* PriceAlteration : productOfferingPrice

PriceAlteration *-right-> "1" Price : price

ProductPrice *-->  "<color:blue>0..1" Price : price

ProductPrice *-[#blue]->  "0..*" PriceAlteration : <color:blue>priceAlteration

GeographicAddressValue *-[#blue]->  "0..1" GeographicSubAddressValue : <color:blue>geographicSubAddress

ProductValue *-left[#blue]-> "0..1" ProductOfferingRef : <color:blue>productOffering

ProductRelationship "0..*" <-[#blue]-* ProductValue : <color:blue>productRelationship

BillingAccountRef "0..1" <-[#blue]-* ProductValue : <color:blue>billingAccount

AgreementItemRef "0..*" <-[#blue]-* ProductValue : <color:blue>agreementItem

Characteristic "0..*" <-[#blue]-* ProductValue : <color:blue>productCharacteristic

RelatedParty "0..*" <-[#blue]-* ProductValue : <color:blue>relatedParty

ProductTerm "0..*" <-[#blue]-* ProductValue : <color:blue>productTerm

ProductValue *-[#blue]->  "0..*" ResourceRef : <color:blue>realizingResource

ProductValue *-[#blue]->  "0..*" ServiceRef : <color:blue>realizingService

ProductValue *-[#blue]->  "0..1" ProductSpecificationRef : <color:blue>productSpecification

GeographicSubAddressValue *-[#blue]->  "0..*" GeographicSubAddressUnit : <color:blue>subUnit

RelatedPlaceRefOrValue ..> GeographicLocationValue

RelatedPlaceRefOrValue ..> PlaceRef

ProductRefOrValue ..> ProductRef




skinparam legendBackgroundColor #transparent
skinparam legendBorderColor #transparent

legend
   |= <size:10>Color |= <size:10>Description |
   | <#FFFFFFF> | <size:10>Sub-resource (sub-graph in current diagram) |
   | <#FCF2E3> | <size:10>Sub-resource |
   | <#FFFFE0> | <size:10>Sub-resource (reference entity) |
   | <#FADADD> | <size:10>Sub-resource with details in separate diagram |
   | <#E6F5F7> | <size:10>Enumeration |
   | <#blue> | <size:10>added |
 <size:10>(1) : Mandatory property
endlegend

@enduml